spring:
  datasource:
    url: jdbc:mysql://localhost:3306/appmusic?useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: "Infor.258852"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        hbm2ddl:
          auto: update
  mvc:
    hiddenmethod:
      filter:
        enabled: true